#!/bin/bash

# check_apc_pdu Nagios plugin to check health of APC PDU (tested on AP7900)
# Copyright (C) 2016 Michael Newton
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

name=$(basename "$0")
usage="
Usage:
    $name -H <hostname> [-2] [-p <port>] [-C <community>] [-t transport] [-w <warning>] [-c <critical>] [-f] [-d]
    $name -H <hostname> -3 -l <secName> [-t transport] [-L <protocolList>] [-x <authPassword>]
        [-X <privPassword>] [-w <warning>] [-c <critical>] [-f] [-d]
    $name -h

    -H hostname         Hostname
    -p port             SNMP port
    -C community        SNMP version 1/2c community (default public)
    -2                  Use SNMP version 2c (default 1)
    -3                  Use SNMP version 3 (default 1)
    -t transport        SNMP transport (udp, tcp, udp6, tcp6; default udp)
    -l secName          SNMP v3 username
    -L protocolList     SNMP v3 authentication, privacy protocols (default md5,des)
    -x authPassword     SNMP v3 authentication password
    -X privPassword     SNMP v3 privacy password
    -w warning          Warning threshold for CPU (%) checks
    -c critical         Critical threshold for CPU (%) checks
    -f                  Output performance data
	-d                  Output debug data
    -h                  Help (print command usage and quit)
"

# set some defaults
version="1"
community="public"
port="161"
protocols="md5,des"
transport="udp"
exit="0"
generate_perf_data="0"
debug="0"
snmpget="/usr/bin/snmpget"
snmp_opts="-OeqvU"
snmp_cmd=("$snmpget" "$snmp_opts")
warn_oid=".1.3.6.1.4.1.318.1.1.12.2.2.1.1.3.1"
crit_oid=".1.3.6.1.4.1.318.1.1.12.2.2.1.1.4.1"

while getopts "H:p:C:23l:L:x:X:w:c:fdh" option; do
	case $option in
		H) hostname=$OPTARG;;
		p) port=$OPTARG;;
		2) version=2c;;
		3) version=3;;
		C) community=$OPTARG;;
		l) secName=$OPTARG;;
		L) protocols=$OPTARG;;
		x) authPassword=$OPTARG;;
		X) privPassword=$OPTARG;;
		w) warning=$OPTARG;;
		c) critical=$OPTARG;;
		f) generate_perf_data=1;;
		d) debug=1;;
		h) echo "$usage" && exit 3;;
	esac
done

if [[ -z "$hostname" ]]
then
	echo "Unknown: Missing hostname or mode parameter"
	echo "$usage"
	exit 3
fi

if [[ "$version" = "3" ]]; then
	if [[ -z "$secName" ]]; then
		echo "Unknown: Missing SNMP v3 security name"
		echo "$usage"
		exit 3
	fi
	snmp_cmd=(${snmp_cmd[@]} "-v" "$version" "-u" "$secName")
	if [[ -z "$authPassword" ]]; then
		secLevel="NoAuthNoPriv"
	else
		authProtocol=${protocols%,*}
		privProtocol=${protocols#*,}
		if [[ -z "$privPassword" ]]; then
			secLevel="AuthNoPriv"
		else
			secLevel="AuthPriv"
			snmp_cmd=(${snmp_cmd[@]} "-x" "$privProtocol" "-X" "$privPassword")
		fi
		snmp_cmd=(${snmp_cmd[@]} "-l" "$secLevel" "-a" "$authProtocol" "-A" "$authPassword")
	fi
	snmp_cmd=(${snmp_cmd[@]} "$transport:$hostname:$port")
else
	if [[ -z "$community" ]]; then
		echo "Unknown: Missing community parameter"
		echo "$usage"
		exit 3
	fi
	snmp_cmd=(${snmp_cmd[@]} "-v" "$version" "-c" "$community" "$transport:$hostname:$port")
fi


if [[ -z "$warning" ]] || [[ -z "$critical" ]]; then
	[[ $debug -gt 0 ]] && printf "Running command: %s %s\n" "${snmp_cmd[*]}" "$warn_oid" "$crit_oid"
	read warn10 crit10 <<< $("${snmp_cmd[@]}" "$warn_oid" "$crit_oid" 2> /dev/null)
	[[ $debug -gt 0 ]] && printf "Returned %d\n" $?
	read warning critical <<< $(echo "scale 1; $warn10 / 10; $crit10 / 10" | bc)
	[[ $debug -gt 0 ]] && printf "Retrieved warning and critical thresholds %d and %d via SNMP\n" "$warning" "$critical"
else
	# can't do bash math in case we get a float
	read warn10 crit10 <<< $(echo "$warning * 10;$critical * 10" | bc)
fi

check_oid=".1.3.6.1.4.1.318.1.1.12.2.3.1.1.2.1"
check_name="Load"
check_unit="A"
[[ $debug -gt 0 ]] && printf "Running command: %s %s\n" "${snmp_cmd[*]}" "$check_oid"
metric=$("${snmp_cmd[@]}" "$check_oid" 2> /dev/null)
[[ $debug -gt 0 ]] && printf "Returned %d\n" $?
if [[ "$metric" =~ [^0-9] ]] || [[ -z "$metric" ]]; then
    status="Unknown"
	exit=3
elif [[ $metric -ge $crit10 ]]; then
    status="Critical"
	exit=2
elif [[ $metric -ge $warn10 ]]; then
    status="Warning"
	exit=1
else
    status="OK"
	exit=0
fi

if [[ $status == "Unknown" ]]; then
	printf "%s: %s %s" "$status" "$check_name" "$metric"
else
    metric=$(echo "scale=1; $metric / 10" | bc)
	if [[ $generate_perf_data = 1 ]]; then 
		printf "%s: %s %0.1f%s|%s=%0.1f;%0.1f;%0.1f" "$status" "$check_name" "$metric" "$check_unit" "${check_name/ /_}" "$metric" "$warning" "$critical"
	else
		printf "%s: %s %0.1f%s" "$status" "$check_name" "$metric" "$check_unit"
	fi
fi

exit $exit
